all: hello times_tables

hello: hello.c
	gcc -Wall -Werror -ggdb3 hello.c -o hello

times_tables: times_tables.c
	gcc -Wall -Werror -ggdb3 times_tables.c -o times_tables

clean:
	rm -f times_tables hello *~

